version: '3.7'
# DevelopMent
services:
  acg-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3007:3007
    volumes:
      - ./src:/acg-alba/src
    env_file:
      - ./.env
      # - ./.env.local
    environment:
      - TZ=Asia/Seoul
